name: XAI-for-Healthcare
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - atk-1.0=2.36.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cairo=1.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - dataclasses=0.8
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fvcore=0.1.5.post20221221
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - ghostscript=10.04.0
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.13
  - graphviz=3.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=70.1
  - imagemagick=7.1.0_35
  - importlib-metadata=8.5.0
  - iopath=0.1.10
  - ipykernel=6.29.5
  - ipython_pygments_lexers=1.1.1
  - jbig=2.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libedit=3.1.20230828
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.43
  - librsvg=2.54.4
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.7
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.7
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openjpeg=2.5.0
  - openssl=3.4.0
  - packaging=24.1
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.43
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.40.0
  - pkg-config=0.29.2
  - platformdirs=4.3.6
  - portalocker=3.0.0
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - accelerate==1.7.0
      - adv-lib==0.2.2
      - albucore==0.0.19
      - albumentations==1.4.20
      - annotated-types==0.7.0
      - bitsandbytes==0.46.0
      - cachetools==5.5.0
      - captum==0.7.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.3.0
      - csv-diff==1.2
      - cycler==0.12.1
      - dictdiffer==0.9.0
      - einops==0.8.0
      - entmax==1.3
      - eval-type-backport==0.2.0
      - evdev==1.7.1
      - filelock==3.13.1
      - fire==0.6.0
      - fonttools==4.53.1
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - google-api-core==2.22.0
      - google-api-python-client==2.149.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - googleapis-common-protos==1.65.0
      - grad-cam==1.5.5
      - httplib2==0.22.0
      - huggingface-hub==0.25.0
      - idna==3.10
      - imageio==2.35.1
      - ipython==8.27.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - line-profiler==4.1.3
      - lxt==2.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - medmnist==3.0.1
      - medmnistc==0.1.0
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - open-clip-torch==2.32.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - pillow==10.2.0
      - pix2tex==0.1.2
      - prompt-toolkit==3.0.47
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pynput==1.7.7
      - pyparsing==3.1.4
      - pyqt6==6.7.1
      - pyqt6-qt6==6.7.3
      - pyqt6-sip==13.8.0
      - pyqt6-webengine==6.7.0
      - pyqt6-webengine-qt6==6.7.3
      - pyqt6-webenginesubwheel-qt6==6.7.3
      - pyside6==6.8.0.2
      - pyside6-addons==6.8.0.2
      - pyside6-essentials==6.8.0.2
      - python-xlib==0.33
      - pytorch-gradcam==0.2.1
      - pytorch-msssim==1.0.0
      - pytz==2024.2
      - quantus==0.5.3
      - regex==2024.9.11
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.23.2
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - shiboken6==6.8.0.2
      - stringzilla==3.10.5
      - sympy==1.12
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - timm==1.0.15
      - tokenizers==0.20.1
      - torch==2.4.1
      - torchaudio==2.4.1
      - torcheval==0.0.7
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.46.0
      - triton==3.0.0
      - ttach==0.0.3
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - visdom==0.2.4
      - wand==0.6.13
      - websocket-client==1.8.0
      - x-transformers==0.15.0
      - xmltodict==0.14.2
      - zennit==0.5.1
prefix: /home/srepetto/miniconda3/envs/XAI-for-Healthcare
